{
 "title": "Network Monitoring Dashboard",
 "time": { "from": "now-5m", "to": "now" },
 "templating": {
  "list": [
   { "name": "duration1", "label": "duration", "query": "5m,10m,30m,1h" },
   { "name": "switches", "query": "2,3,5,10" },
   { "name": "interfaces", "query": "2,3,5,10" }
  ]
 },
 "panels": [
  { "title": "Infrastructure Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Resource Utilization",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "ovs_resource_utilization", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "CPU Utilization",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "ovs_cpu_utilization", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Bridge Controller Status",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "targets": [
    {
     "expr": "bottomk($switches,ovs_bridge_controller_status)",
     "legendFormat": "{{switch}}"
    }
   ]
  },
  {
   "title": "Memory Per Bridge (in MB)",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "decmbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "ovs_memory_per_bridge", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Rate of Port Flapping ",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
   "targets": [
    {
     "expr": "topk($interfaces,rate(ovs_port_flapping[$duration1]))",
     "legendFormat": "{{switch}}"
    }
   ]
  },
  {
   "title": "Database Utilization",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "ovs_db_space_utilization", "legendFormat": "__auto" }
   ]
  },
  { "title": "Mice Flows", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 25 } },
  {
   "title": "Flow Table Utilization",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "topk($switches,ovs_flow_utilization)",
     "legendFormat": "{{switch}}"
    }
   ]
  },
  {
   "title": "Flow entry modification velocity",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "topk($switches,rate(ovs_flows_modification[$duration1]))",
     "legendFormat": "{{switch}}"
    }
   ]
  },
  {
   "title": "Packet In ",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "topk($switches, rate(ovs_packet_in[$duration1]))",
     "legendFormat": "{{switch}}"
    }
   ]
  },
  {
   "title": "Asymmetric Traffic Volume",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "topk($interfaces,delta(ovs_inbound_outbound[$duration1])/delta(ovs_total_bytes_interface[$duration1]) * 100)",
     "legendFormat": "{{interface}}"
    }
   ]
  },
  {
   "title": "Elephant Flows",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 42 },
   "collapsed": true,
   "panels": [
    {
     "title": "Packets per flow",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 59 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "topk($switches,ovs_average_packets_per_flow)",
       "legendFormat": "{{switch}}"
      }
     ]
    },
    {
     "title": "Interface Utilization %",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 59 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "topk($interfaces,rate(ovs_interface_bytes[1m])/(ovs_interface_link_speed * 60) * 100) ",
       "legendFormat": "{{interface}}"
      }
     ]
    },
    {
     "title": "Average Flow Duration",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 67 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "topk($switches,ovs_average_flow_duration)",
       "legendFormat": "{{switch}}"
      }
     ]
    },
    {
     "title": "Flow Stability Index",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 67 },
     "targets": [
      {
       "expr": "bottomk($switches,ovs_flow_stability_index)",
       "legendFormat": "{{switch}}"
      }
     ]
    }
   ]
  }
 ]
}